version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      trpc:
        patterns:
          - '@trpc/*'
      docusaurus:
        patterns:
          - '@docusaurus/*'
    reviewers:
      - '@ExpediaGroup/comparadise-committers'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - '@ExpediaGroup/comparadise-committers'
