version: 2
updates:
  #  - package-ecosystem: 'pnpm'
  #    directory: '/'
  #    schedule:
  #      interval: 'weekly'
  #    reviewers:
  #      - '@ExpediaGroup/comparadise-committers'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - '@ExpediaGroup/comparadise-committers'
