name: 'comparadise'
description: 'A Github Action for using Comparadise with visual regression tests'
author: 'Dan Adajian'
inputs:
  visual-test-command:
    description: 'The command that runs your visual tests. Can be multiple lines!'
    required: true
  bucket-name:
    description: 'The S3 bucket name'
    required: true
  commit-hash:
    description: 'The commit hash'
    required: true
  screenshots-directory:
    description: 'The directory where your visual tests expect screenshots to be'
    required: false
    default: screenshots
  package-paths:
    description: 'Comma separated list of package paths for monorepos'
    required: false
  comparadise-host:
    description: 'The URL at which you are hosting Comparadise'
    required: false
  comment-details:
    description: 'Additional details you would like to leave on the Comparadise comment'
    required: false
  github-token:
    description: 'The GitHub access token'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'action/dist/index.js'
branding:
  icon: layout
  color: green
