name: Publish

on:
  pull_request:
    branches:
      - main
#  release:
#    types: [created]

jobs:
  #  publish-docker:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Docker meta
  #        id: meta
  #        uses: docker/metadata-action@v4
  #        with:
  #          images: |
  #            expediagroup/comparadise
  #          tags: |
  #            type=ref,event=tag
  #
  #      - name: Set up QEMU
  #        uses: docker/setup-qemu-action@v2
  #
  #      - name: Set up Docker Buildx
  #        uses: docker/setup-buildx-action@v2
  #
  #      - name: Login to DockerHub
  #        uses: docker/login-action@v2
  #        with:
  #          username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
  #
  #      - name: Build and push
  #        uses: docker/build-push-action@v4
  #        with:
  #          push: true
  #          tags: ${{ steps.meta.outputs.tags }}
  #          labels: ${{ steps.meta.outputs.labels }}

  publish-comparadise-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Install
        run: pnpm --filter comparadise-utils install

      - name: Publish
          # echo VERSION_TAG=$(echo "${GITHUB_REF}" | cut -d "/" -f3) >> $GITHUB_OUTPUT
        run: |
          echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} >> .npmrc
          echo VERSION_TAG=v0.2.9 >> $GITHUB_OUTPUT
          pnpm --filter comparadise-utils bump-version
          pnpm --filter comparadise-utils publish --no-git-checks

#  publish-tags:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Update Major Version
#        run: |
#          MAJOR_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3 | cut -d "." -f1)
#          echo "New version: ${MAJOR_VERSION}"
#          git tag ${MAJOR_VERSION}
#          git push --tags -f
