name: Release

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/release.yml'
      - 'public/**'
      - 'server/**'
      - 'src/**'
      - '.nvmrc'
      - 'Dockerfile'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Release
        run: npx semantic-release@v19.0.5 --debug --no-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
